from os import getenv

SQLALCHEMY_DATABASE_URI = getenv('POSTGRES_URL')
SQLALCHEMY_TRACK_MODIFICATIONS = False 
JWT_SECRET_KEY = getenv('JWT_SECRET_KEY')
JWT_HEADER_TYPE = None
REDIS_URL = getenv('REDIS_URL')