"""finished Stock and Order model

Revision ID: 21e6905856e1
Revises: 35f78fa01873
Create Date: 2021-10-06 14:15:06.523968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e6905856e1'
down_revision = '35f78fa01873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=6), nullable=False),
    sa.Column('company', sa.String(length=120), nullable=False),
    sa.Column('prev_close', sa.Float(decimal_return_scale=2), nullable=False),
    sa.Column('market_price', sa.Float(decimal_return_scale=2), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('price_per_share', sa.Float(decimal_return_scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('stock')
    # ### end Alembic commands ###
