"""finished StockData model

Revision ID: cef206444493
Revises: b2fc3cd134da
Create Date: 2021-10-06 14:23:02.119153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef206444493'
down_revision = 'b2fc3cd134da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('prev_close', sa.Float(decimal_return_scale=2), nullable=False),
    sa.Column('market_price', sa.Float(decimal_return_scale=2), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_data')
    # ### end Alembic commands ###
