"""changed Account password length to support hashing

Revision ID: e240778debdc
Revises: cef206444493
Create Date: 2021-10-14 21:38:01.426071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e240778debdc'
down_revision = 'cef206444493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
