"""Initial migration

Revision ID: fc7395ceb567
Revises: 
Create Date: 2021-10-06 08:26:47.732625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc7395ceb567'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('equity_prev_close', sa.Float(decimal_return_scale=2), nullable=False),
    sa.Column('portfolio_equity', sa.Float(decimal_return_scale=2), nullable=False),
    sa.Column('buying_power', sa.Float(decimal_return_scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    # ### end Alembic commands ###
